config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  resources :users do
    collection do
      delete :bulkdelete, to: "users#bulk_delete"
    end
  end 

  post "seedusers", to: "users#seed_users"

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors.add attribute, (options[:message] || "is not an email")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :expire_cache
  after_destroy :expire_cache

  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true, email: true

 def expire_cache
   ActionController::Base.new.expire_fragment('table_of_users')
 end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :set_user, only: %i[ show update destroy ]

  def index
   @users = User.all
   render json: @users
  end

  def show
    render json: @user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user, status: :created, location: api_vi_user_url(@user)
    else
      render json: @user.errors, status: :unprocessable_entity 
    end
  end

  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity 
    end
  end

  def destroy
    @user.destroy
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :ls)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: %i[ show edit update destroy ]

  def index
    users = User.where(is_deleted: false)
    if params[:query].present?
      users = users.where("first_name Like ?", "%#{params[:query]}%").or(User.where("email Like ?", "%#{params[:query]}%")) 
    elsif params[:filter_option].present?
      users = users.where("#{params[:filter_option]} Like ?", "%#{params[:filter]}%")
    end
    @pagy, @users = pagy(users, items: 5)
  end

  def show 
  end

  def new 
    @user = User.new 
  end

  def create 
    @user = User.new(user_params) 
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "User successfully created." }
        format.turbo_stream { flash.now[:notice] = "User successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit 
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "User successfully updated." }
        format.turbo_stream { flash.now[:notice] = "User successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }  
      end
    end
  end

  def destroy
    @user.is_deleted = true

    UserMailer.user_deleted(@user).deliver_later(wait: 30.minutes)

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User successfully deleted." }
      format.turbo_stream { flash.now[:notice] = "User successfully deleted." }
    end
  end
  
  def bulk_delete 
    # User.destroy_by(id: params[:user_ids])
    @users = User.find(params[:user_ids])
    @users.each do |user|
      user.is_deleted = true
      user.save
      UserMailer.user_deleted(user).deliver_later(wait: 30.minutes)
    end

    respond_to do |format|
      format.html { redirect_to users_path, notice: "Users successfully deleted." }
    end
  end 

  def seed_users
    User.destroy_all

    UserReaderService.call
  end

  def clear_filter
    clear_session(:filter_option, :filter)
    @users = Users.all
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone)
    end

    def set_users
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sloopers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "partials/nav" %>
    <div id="flash">
      <%= render 'partials/flash' %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-4xl font-semibold">Welcome To Sloopers</h1>
<%= button_to "Get users", seedusers_path, remote: true, class: "btn btn-sm btn-info" %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-controller="flash" class="flex justify-between alert alert-info" role="alert">
    <div class="flex">
      <svg class="flex-shrink-0 w-5 h-5 text-blue-700" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <div class="ml-3 text-sm font-medium text-blue-700">
        <%= msg %>
      </div>
    </div>
    <div data-action="click->flash#dismiss">
      <span class="sr-only">Dismiss</span>
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </div>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <a class="btn btn-ghost normal-case text-xl">🎉</a>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li><%= link_to "Users", users_path %></li>
    </ul>
  </div>
</div>

app/views/users/_filter_form.html.erb
<div>
  <%= form_with url: users_path, method: :get, data: { controller: "search-form",
                                                           turbo_action: "advance",
                                                           turbo_frame: "users" }, class: "flex" do |form| %>
      
   <%= select_tag "filter_option", 
     options_for_select([[ "First name", "first_name"], ["Last name", "last_name"]]),
     prompt: "Pick a filter", class: "select selected-bordered mr-2"
   %>

    <%= form.text_field :filter,
      placeholder: "Filter", 
      class: "input input-bordered w-full", 
      autocomplete: "off", 
      data: { action: "input->search-form#search" } 
    %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-error shadow-lg">
      <div>
        <div>
          <h2 class="text-red-900">
            <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:
          </h2>
          <% user.errors.each do |error| %>
            <p><%= error.full_message %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="grid grid-cols-5 gap-4">
    <div class="form-control">
      <%= form.label :first_name, class: "hidden" %>
      <%= form.text_field :first_name, class: "input input-bordered w-full bg-white" %>
    </div>

    <div class="form-control">
      <%= form.label :last_name, class: "hidden" %>
      <%= form.text_field :last_name, class: "input input-bordered w-full bg-white" %>
    </div>

    <div class="form-control">
      <%= form.label :email, class: "hidden" %>
      <%= form.text_field :email, class: "input input-bordered w-full bg-white" %>
    </div>

    <div class="form-control">
      <%= form.label :phone, class: "hidden" %>
      <%= form.text_field :phone, class: "input input-bordered w-full bg-white" %>
    </div>

    <div class="flex items-end gap-2">
      <%= form.submit "Save", class: "btn btn-sm btn-primary" %>
      <%= link_to "Cancel", users_path, class: "btn btn-sm mr-2" %>
    </div>
  </div>
<% end %>

app/views/users/_search_form.html.erb
<div>
  <%= form_with url: users_path, method: :get, data: { controller: "search-form",
                                                           turbo_action: "advance",
                                                           turbo_frame: "users" } do |form| %>
    <%= form.text_field :query,
      placeholder: "Search Name or Email", 
      class: "input input-bordered w-full", 
      autocomplete: "off", 
      data: { action: "input->search-form#search" } 
    %>
  <% end %>
</div>

app/views/users/_user.html.erb
<%= turbo_frame_tag user do %>
  <div class="flex">
    <div class="py-4 px-2"><%= check_box_tag "user_ids[]", user.id %></div>
    <div class="w-full grid grid-cols-5 gap-4 py-4">
      <div class="col-span-1"><%= link_to user.first_name, user_path(user) %></div>
      <div class="col-span-1"><%= user.last_name %></div>
      <div class="col-span-1 overflow-hidden"><%= user.email %></div>
      <div class="col-span-1"><%= user.phone %></div>
      <div class="flex">
        <%= link_to "Edit", edit_user_path(user), class: "btn btn-sm btn-success mr-4" %>
        <%= button_to "Delete", user_path(user), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-sm btn-error" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.update User.new, "" %>
<%= turbo_stream.update "flash", partial: "partials/flash" %>

app/views/users/deleteall.turbo_stream.erb
<%= turbo_stream.update "flash", partial: "partials/flash" %>

app/views/users/destroy.turbo_stream.erb
<%= turbo_stream.remove "user_#{@user.id}" %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= turbo_frame_tag @user do %>
  <%= render "form", user: @user %>
<% end %>

app/views/users/index.html.erb
<div class="w-full">
  <div class="m-8">
    <div class="flex justify-between">
      <h1 class="font-bold text-4xl my-4">Users</h1>
      <%= link_to "New User", new_user_path, data: { turbo_frame: dom_id(User.new) }, class: "btn btn-sm btn-primary" %>
    </div>
    <div class="flex justify-between my-4">
      <%= render "search_form" %>
      <div class="flex gap-2">
        <%= render "filter_form" %>
        <%= button_to "Clear filter", users_path, method: :get, class: "btn btn-sm", form: { class: "my-2"} %>
      </div>
    </div>
    <%= form_with url: bulkdelete_users_path, method: :delete, data: { turbo_frame: "_top" } do |form|  %>
      <%= submit_tag "Bulk Delete", class: "btn btn-sm btn-error" %>
      <% cache('table_of_users') do %>
        <div class="flex">
          <div class="px-4"></div>
          <div class="w-full py-4 grid grid-cols-5 gap-4 font-bold">
            <div>First name</div>
            <div>Last name</div>
            <div>Email</div>
            <div>Phone</div>
            <div></div>
          </div>
        </div>
        <%= turbo_frame_tag User.new %>
        <%= turbo_frame_tag "users" do %>
          <%= render @users %>
          <div class="my-2">
            <%== pagy_nav(@pagy, link_extra: 'data-turbo-action="advance"') if @pagy.pages > 1 %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= turbo_frame_tag @user do %>
  <%= render "form", user: @user %>
<% end %>

app/views/users/update.turbo_stream.erb
<%= turbo_stream.replace @user %>
<%= turbo_stream.replace "flash", partial: "partials/flash" %>